#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

commit_lint() {
    if git-branch-is -q -r "^(master)"; then
        commitlint --edit
    else
        true
    fi
}

build_hybrid() {
    set -x
    rm -rfv dist
    formats=('cjs' 'esm')
    for format in ${formats[*]}; do
        npx tsup src/index.ts -d=dist/${format} --keep-names --format=${format} --target=es2020 --external=reflect-metadata --sourcemap
    done
    npx tsup src/index.ts -d=dist --dts-only
    echo {\"type\": \"module\"} >dist/esm/package.json
    echo {\"type\": \"commonjs\"} >dist/cjs/package.json
    cp -fv README.md LICENSE dist
    cat package.json | jq "del(.type)" >dist/package.json
}

"$@"
