#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

commit_lint() {
    if git-branch-is -q -r "^(master)"; then
        commitlint --edit
    else
        true
    fi
}

build_hybrid() {
    set -x
    rm -rfv dist
    npx tsup src/index.ts -d=dist/mjs --keep-names --format=esm --target=es2020 --external=reflect-metadata --sourcemap
    npx tsup src/index.ts -d=dist/cjs --keep-names --format=cjs --target=es2020 --external=reflect-metadata --sourcemap
    npx tsup src/index.ts -d=dist --dts-only
    echo {\"type\": \"module\"} >dist/mjs/package.json
    echo {\"type\": \"commonjs\"} >dist/cjs/package.json
    cp -fv README.md LICENSE dist
    cat package.json | jq "del(.type)" >dist/package.json
}

"$@"
