#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

commit_lint() {
  if git-branch-is -q -r "^(master)"; then
    commitlint --edit
  else
    true
  fi
}

build_pkgroll() {
  set -x
  rm -rf dist
  mkdir dist
  # https://esbuild.github.io/api/#target
  npx pkgroll --target=es2024
  cp -f README.md dist
  cat package.json | jq '.main = "./index.cjs"' |
    jq '.module = "./index.mjs"' |
    jq '.types = "./index.d.ts"' |
    jq '.exports.".".import = "./index.mjs"' |
    jq '.exports.".".require = "./index.cjs"' \
      >dist/package.json
  set +x
}

"$@"
